### ISSUE TITLE
awus036ac with BigSur 11.5.1

### ISSUE THREAD

**Issue by Shane1033** [chris1111/Wireless-USB-Big-Sur-Adapter#134]
what is the latest version of Big Sur 11 that this driver works with as I'm trying to install it  on 11.5.1 and its till not recognised, I'm willing to downgrade my MacBook but would like the latest version that's compatible for security sake? I'm using the alfa awus036ac wireless adapter on a MacBook Pro 2020

any help is appreciated

thanks

**Comment by CaaioSB** [comment]
As much as my device is different, I believe the problem is not with the application, after all, I've updated mine to version 11.5.1 now and my TP-LINK WN725N is still working normally, there's an [issue](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/131), try to do it the steps I indicate there to test :D
